In [12]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv(r'Desktop\OnlineRetail.csv',encoding='unicode_escape')
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

           InvoiceDate  UnitPrice  CustomerID         Country
0        12-01-10 8:26       2.55     17850.0  United Kingdom
1        12-01-10 8:26       3.39     17850.0  United Kingdom
2        12-01-10 8:26       2.75     17850.0  United Kingdom
3        12-01-10 8:26       3.39     17850.0  United Kingdom
4        12-01-10 8:26       3.39     17850.0  United Kingdom
...                ...        ...         ...             ...
541904  12-09-11 12:50       0.85     12680.0          France
541905  12-09-11 12:50       2.10     12680.0          France
541906  12-09-11 12:50       4.15     12680.0          France
541907  12-09-11 12:50       4.15     12680.0          France
541908  12-09-11 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [15]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12-01-10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-10 8:26,3.39,17850.0,United Kingdom

In [17]:
df['Description'] = df['Description'].str.strip()
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]

In [19]:
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3

           InvoiceDate  UnitPrice  CustomerID         Country
0        12-01-10 8:26       2.55     17850.0  United Kingdom
1        12-01-10 8:26       3.39     17850.0  United Kingdom
2        12-01-10 8:26       2.75     17850.0  United Kingdom
3        12-01-10 8:26       3.39     17850.0  United Kingdom
4        12-01-10 8:26       3.39     17850.0  United Kingdom
...                ...        ...         ...             ...
541904  12-09-11 12:50       0.85     12680.0          France
541905  12-09-11 12:50       2.10     12680.0          France
541906  12-09-11 12:50       4.15     12680.0          France
541907  12-09-11 12:50       4.15     12680.0          France
541908  12-09-11 12:50       4.95     12680.0          France

[532621 rows x 8 columns]

In [20]:
basket = (df[df['Country'] =="France"]
          .groupby(['InvoiceNo', 'Description'])['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))

In [21]:
basket.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1

basket_sets = basket.applymap(encode_units)
basket_sets.drop('POSTAGE', inplace=True, axis=1)

In [33]:
pip install apyori

Collecting apyoriNote: you may need to restart the kernel to use updated packages.
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py): started

  Building wheel for apyori (setup.py): finished with status 'done'
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5979 sha256=c0126cfca3310bc409316ad7543a1d5a62970b7fb6cd95aa221ea0f1d70bf1c0
  Stored in directory: c:\users\new\appdata\local\pip\cache\wheels\1b\02\6c\a45230be8603bd95c0a51cd2b289aefdd860c1a100eab73661
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [34]:
from apyori import apriori
frequent_itemsets = apriori(basket_sets, min_support=0.05, use_colnames=True)

In [40]:
pip install mlxtend

Collecting mlxtendNote: you may need to restart the kernel to use updated packages.
  Downloading mlxtend-0.18.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: numpy>=1.16.2 in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (1.19.2)

Requirement already satisfied: matplotlib>=3.0.0 in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (3.3.1)
Requirement already satisfied: pandas>=0.24.2 in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (1.1.3)
Requirement already satisfied: setuptools in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (50.3.1.post20201107)
Requirement already satisfied: joblib>=0.13.2 in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (0.17.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: scikit-learn>=0.20.3 in c:\users\new\anaconda3\lib\site-packages (from mlxtend) (0.23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\new\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (8.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\new\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\new\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: certifi>=2020.06.20 in c:\users\new\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2020.6.20)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\new\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\new\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\new\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2020.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\new\anaconda3\lib\site-packages (from scikit-learn>=0.20.3->mlxtend) (2.1.0)
Requirement already satisfied: six>=1.5 in c:\users\new\anaconda3\lib\site-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.18.0

In [42]:
from mlxtend.frequent_patterns import association_rules

In [55]:
df.shape

(532621, 8)

In [ ]:
records=[]
for i in range(0,532621):
    records.append([str(df.values[i,j]) for j in range(0,8)])

In [ ]:
for sets in records:
    print(sets)

In [ ]:
association_rules=apriori(records,min_support=0.5,min_confidence=0.7,min_length=2)

In [ ]:
association_results=list(association_rules)

In [ ]:
print(len(association_results))

In [ ]:
association_results[0]

In [ ]:
for item in association_results:
    pair = item[0]
    items = [x for x in pair]
    print("Rule :"+ str(item[0]) + "->" + str(item[1]))
    print("Support : {}".format(item[1]))
    print("Confidence : {}".format(item[2][0][2]))
    print("Lift : {}".format(item[2][0][3]))
    print("\n------------------------------------------------\n")